### ISSUE TITLE
Ajout d'une licence

### ISSUE THREAD

**Issue by bzg** [etalab/de-quality-processing#1]
Hello, il faudrait une licence sur le dépôt : tu peux regarder comment fait https://github.com/etalab/data-codes-sources-fr par exemple. Si tu as besoin d'un coup de main, je peux faire la PR. Merci !

**Comment by geoffreyaldebert** [comment]
Hello, la licence est mise. Je close l'issue. Merci !

**Comment by bzg** [comment]
Merci à toi !
